spring.application.name=gate
# Define explicitamente o driver do CsvJdbc
spring.datasource.driver-class-name=org.relique.jdbc.csv.CsvDriver

# URL apontando para o diretório dos arquivos
spring.datasource.url=jdbc:relique:csv:/Users/drt67801/Desktop/teste

# Como o CSV não suporta comandos de criação de tabela (DDL), desabilite o Hibernate de tentar alterar o schema
spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.HSQLDialect
